import { Router } from "express";
import { register, login, logout, me, claimFirstAdmin, changePassword  } from "../controllers/authController.js";
import { requireAuth } from "../middleware/auth.js";
const router = Router(); 
router.post("/register", register);
 router.post("/login", login); 
 router.post("/logout", logout); 
 router.get("/me", requireAuth, me); 
 router.post("/claim-first-admin", requireAuth, claimFirstAdmin);
 router.patch("/password", requireAuth, changePassword);
  export default router;
